### ISSUE TITLE
Add link to SAP BTP Trial tutorial

### ISSUE THREAD

**Issue by nicoschoenteich** [SAP-samples/cap-service-integration-codejam#41]
Maybe we should think about adding a link to the [SAP BTP Trial Tutorial](https://developers.sap.com/tutorials/hcp-create-trial-account.html) at [this step here](https://github.com/SAP-samples/cap-service-integration-codejam/tree/main/exercises/01-set-up-workspace#primary-environment-a-dev-space-in-the-sap-business-application-studio), in case attendees want to use the SAP Business Application Studio, but don't have a subscription yet.

**Comment by qmacro** [comment]
Sorry Nico, closed before I'd made the change. I've added a link to the tutorial in the prerequisites. I think it's better there, rather than clutter up the exercises with something that should be done before the CodeJam starts.
