### ISSUE TITLE
Session Feedback

### ISSUE THREAD

**Issue by laurensvanrijn** [SAP-samples/cap-service-integration-codejam#7]
Thanks for taking a couple of minutes to give feedback, which will help me improve for next time. **Before doing anything else, hit the green button "Submit new issue" right now to save this issue content, rather than try to complete the feedback in this raw form.** Then go through the questions and mark a single checkbox for each, to represent your answer. Finally, in the empty comment box below this one, please describe what you liked and what you didn't like.

**What was your experience of CAP before this session?**

- [ ] None
- [X] Basic
- [ ] Intermediate
- [ ] Advanced

**Did this session meet your expectations?**

- [ ] Not really
- [ ] Somewhat
- [X] Mostly
- [ ] Fully

**Was the time allotted to each exercise enough for you to work through them?**

- [ ] Not really
- [X] On the whole, yes

**What did you think of the extra information, explanations and narratives in the exercises?**

- [ ] Too much information
- [ ] Didn't really read it, didn't really bother me though
- [X] Found it helpful as context and background

**How did you find the way we all moved at the same pace through the exercises?**

- [X] Would have preferred to go through them on my own at my own speed
- [ ] Didn't mind, no strong feelings either way
- [ ] Found it useful to keep pace and discuss the exercise questions, and reflect

**How did you find the actual individual (👉) tasks in the exercises?**

- [ ] Not relevant enough
- [ ] Hard to do
- [X] About right
- [ ] Helpful and useful

**How confident are you in being able to start mashing up services in CAP?**

- [X] Still don't understand how things fit together
- [ ] I get it now in theory, just need a bit more time
- [ ] Confident enough to start integrating services

**Which environment(s) did you use?**

- [X] A Dev Space in SAP Business Application Studio
- [ ] VS Code + dev container

If you have time, please add a comment below to write free-form what you liked and what you disliked about the session. Thanks!

1) 
Please start with a demo of what we see in the UI in exercise 12 so everybody has an idea of what we're working towards at the beginning of the CodeJam. Exercise 12 may not always be completed at the end of the CodeJam.

2)
Please add a "recap" at the beginning of each excercise so it's clear which services are running or should be running.

**Comment by qmacro** [comment]
Thanks - those are great comments. 

On point nr 1, I will definitely consider doing a demo of the UI from exercise 12, although I didn't this time as it was only a bonus exercise and I didn't want to give the impression that the CodeJam was UI focused. But worth thinking about how I can point to "the journey's destination before we set off". 

On point nr 2, I've gone through and made a few changes so that it's clearer what has to be started / stopped when.
